config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "questions#index"

  resources :questions do
    resources :answers, shallow: true
  end

  resources :attachments, only: [:destroy]

  patch 'best/:id', to: 'answers#best', as: 'best_answer'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachable
  validates :body, :question_id, :user_id, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  default_scope { order(best: :desc, created_at: :asc )}

  def set_best
    unless best
        self.question.answers.update_all(best: false)
        self.update(best: true)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true, optional: true
  validates :file, presence: true

  mount_uploader :file, AttachmentUploader
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :attachments, as: :attachable

  validates :title, :body, :user_id, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank


  def best_answer
    @best_answer ||= self.answers.find_by(best: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers

  def author_of?(resource)
    resource.user_id == id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: :create
  before_action :load_answer, only: [:best, :update, :destroy]

  def best
    if current_user.author_of?(@answer.question)
      @answer.set_best
    else
      render json: {}, status: :forbidden
    end
  end

  def create
    @answer = @question.answers.build(answer_params.merge(user: current_user))
    if @answer.save
      flash[:notice] = 'Your answer successfully created.'
    end
  end

  def update
    if current_user.author_of?(@answer)
      @answer.update(answer_params)
    else
      redirect_to @answer.question
    end
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy
      flash[:notice] = 'Your answer successfully deleted.'
    else
      flash[:notice] = 'You are not the author.'
    end
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :_destroy, :file])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :load_attachment
  respond_to :js

  def destroy
    @attachment.destroy if current_user.author_of?(@attachment.attachable)
  end

  private

  def load_attachment
    @attachment = Attachment.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.build
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      flash[:notice] = 'Your question successfully created.'
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if current_user.author_of?(@question)
      @question.update(question_params)
    else
      redirect_to @question
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      flash[:notice] = 'Your question successfully deleted.'
      redirect_to questions_path
    else
      flash[:notice] = 'You are not the author'
      redirect_to @question
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :_destroy, :file])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div class="answer-#{answer.id} #{'best-answer' if answer.best}"
    p=answer.body
    p
      - if answer.attachments.any?
        .attachments
          ul
            = render answer.attachments
    -if user_signed_in? && current_user.author_of?(answer)
      p= link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
      p= link_to 'Edit answer', '', class: 'edit-answer-link', data: { answer_id: answer.id}
      p
        = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
          .answer-errors
          = f.label :body, 'Answer'
          = f.text_area :body
          = f.submit 'Save'
          br
          .links
            = link_to_add_association 'add attachments', f, :attachments, partial: 'attachments/attachment_fields'
    -if user_signed_in? && current_user.author_of?(answer.question)
      p= link_to 'Best answer!', best_answer_path(answer), method: :patch, remote: true, class: 'best-answer-link', data: { answer_id: answer.id}

app/views/answers/best.js.erb
answer = $('.answer-<%= @answer.id %>').detach();
$('.answers > h4').after(answer);

$('.best-answer').removeClass('best-answer');
$('.answer-<%= @answer.id %>').addClass('best-answer');

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.new-answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('form.new_answer > #answer_body').val('');
  $('.new-answer-errors').html('');
  $(".notice").html("<%= flash[:notice] %>");
<% end %>

app/views/answers/destroy.js.erb
$('.answer-<%= @answer.id %>').remove();
$(".notice").html("<%= flash[:notice] %>");

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  $('.answer-<%= @answer.id %> > form > .answer-errors').html('');
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-<%= @answer.id %> > form > .answer-errors').append('<%= j message %>');
  <% end %>
<% else %>
  <% if remotipart_submitted? %>
    $('.answer-<%= @answer.id %>').replaceWith("<%= j "#{render @answer}" %>");
  <% else %>
    $('.answer-<%= @answer.id %>').replaceWith('<%= j render @answer %>');
  <% end %>
    $(".notice").html("<%= flash[:notice] %>");
<% end %>

app/views/attachments/_attachment.html.slim
li class="attachment-#{attachment.id}"
  = link_to attachment.file.identifier, attachment.file.url
  = link_to 'delete', attachment_path(attachment), method: :delete, remote: true if user_signed_in? && current_user.author_of?(attachment.attachable)

app/views/attachments/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file
  .field
    = f.file_field :file
  = link_to_remove_association "remove attachment", f

app/views/attachments/destroy.js.erb
$('.attachment-<%= @attachment.id %>').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
      <%="Welcome #{current_user.email}!"%>
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %><hr/>
    <% else %>
      <%= link_to 'Sign in / Sign up', new_user_session_path %>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/questions/_question.html.slim
h3=@question.title
p=@question.body
p
  - if @question.attachments.any?
    .attachments
      ul
        = render @question.attachments
-if user_signed_in? && current_user.author_of?(@question)
  p=link_to 'Delete question', question_path(@question), method: :delete
  p=link_to 'Edit question', '', class: 'edit-question-link'
  = form_for @question, remote: true do |f|
    .question-errors
    = f.label :title
    = f.text_field :title
    br
    = f.label :body
    = f.text_area :body
    = f.submit 'Save'
    br
    .links
      = link_to_add_association 'add attachments', f, :attachments, partial: 'attachments/attachment_fields'

app/views/questions/index.html.slim
ul
  -@questions.each do |q|
    li= link_to q.title, q

p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body

  p Attachments:
  p
  .links
    = link_to_add_association 'add attachments', f, :attachments, partial: 'attachments/attachment_fields'


  = f.submit 'Create'

app/views/questions/show.html.slim
.question
  = render @question

.answers
  -if @question.answers.any?
    h4 Answers:
    =render @question.answers

.new-answer
  = form_for [@question, @answer], remote: true do |f|
    .new-answer-errors
    = f.label :body
    = f.text_area :body
    br
      .links
        = link_to_add_association 'add attachments', f, :attachments, partial: 'attachments/attachment_fields'
    = f.submit 'Give answer'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $('.question-errors').html('');
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').append('<%= j message %> <br/>');
  <% end %>
<% else %>
  $('.question').html('<%= j render @question %>');
  $(".notice").html("<%= flash[:notice] %>");
<% end %>